version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '9906:80'
        volumes:
            - ./src:/var/www/html

    db:
        image: 'mysql'
        restart: always
        environment:
            MYSQL_DATABASE: blog
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./database/blog.sql:/docker-entrypoint-initdb.d/blog.sql
            - db_data:/var/lib/mysql


    adminer:
        image: adminer
        restart: always
        ports:
            - '8100:8080'
        environment:
            - PMA_ARBITRARY=1

volumes:
    db_data: